### ISSUE TITLE
Blank page when creating new server

### ISSUE THREAD

**Issue by Fuzzo** [redhat-developer/rsp-server-community#113]
When I click to create a new server, choose Local, select the server home directory, then what I get is a blank page with 2 buttons:
![image](https://user-images.githubusercontent.com/6161201/159468503-4b439477-4f8f-476b-beae-e531dc49d56e.png)

**Comment by robstryker** [comment]
Sometimes this happens if you load the page immediately starting after vscode, but I'm unable to replicate it in any other situation.  I don't think there's much I can do here for the former, if the workspace isn't fully initialized yet. 

Let me know if attempts to re-open the wizard function normally?

**Comment by robstryker** [comment]
Closing old issue; unable to replicate currently.
