### ISSUE TITLE
possibility to set environment variables for (tomcat) server in json config file

### ISSUE THREAD

**Issue by ubivent-seuffert** [redhat-developer/rsp-server-community#124]
I was hoping to be able to set environment variables for a tomcat server. This does not seem to be possible atm

as far as i understand the code, `PROPERTY_LAUNCH_ENV` is currently not yet set/supported in the regarding ServerDelegate (only  `PROPERTY_PROGRAM_ARGS` & `PROPERTY_VM_ARGS`). 

is there another way to add environment variables to a server config?

**Comment by ubivent-seuffert** [comment]
i also tried using the tomcat `setenv.sh` script in the bin dir of the downloaded tomcat installation. sadly it seems the start scripts are not used by the vscode extension.

**Comment by robstryker** [comment]
If you edit your server file (right click on the server, edit server), you can add something like the following to your file and it *should* automatically append these fields to your environment when starting your server:

```
  "mapProperty.launch.env": {
        "a": "b"
  }
```

**Comment by robstryker** [comment]
I've made another commit today (not released yet though) that ensures that the vscode environment gets passed to the RSP server, which in turn should pass it to the tomcat or wildfly or whatever you're trying to launch. I think this issue is pretty well fixed now, and it should be in the next release. Good luck!

https://github.com/redhat-developer/rsp-server-community/issues/131
