### ISSUE TITLE
Tomcat server doesn't use setenv.sh

### ISSUE THREAD

**Issue by imaperson** [redhat-developer/rsp-server-community#178]
When running a tomcat server, setenv.sh in the tomcat home directory is not used as it is when running via catalina.sh.  Can running a tomcat server set environment variables with setenv.sh?

**Comment by robstryker** [comment]
The setenv.sh script is used exclusively by the shell scripts that launch tomcat. For example, having a JAVA_HOME=/path/to/your/java is used only by the shell script to know what java runtime to use to begin launching the proper tomcat runtime jars. The runtime jars themselves never use these variables. 

Since we are launching the java command ourself, there's no real value to reading the setenv.sh script. It won't do anything for us because we don't look in the same places that `startup.sh` might look for these details. 

If you want to change the VM used to launch tomcat, instead of trying to change the JAVA_HOME environment variable, you should locate your server in the `Servers` view, right click on it, select `Edit Server`,  and change or add the `vm.install.path` property to the json file and make the value the java instance you would like to use. 


I'm no expert on setenv.sh, but, if you can uise that script to pass actual environment variables to the launched tomcat instance, we can do that as well, but through a different mechanism.  If your goal is to pass actual environment variables to your tomcat instance, variables of your own choosing like MYKEY=my.var,  then you can do the following:

Edit your server as above, and add the following to your json: 
  "mapProperty.launch.env": {
        "MYKEY": "my.var"
  }



It might be helpful if we know what you're trying to do here.

**Comment by imaperson** [comment]
The goal was to debug tomcat in development as close as possible some production instances which have specified environment variables in setenv.sh.  I can get by for now by copy/pasting entries into "mapProperty.launch.env" to ensure the same variables exist as they would when running tomcat standalone.  Figured maybe there was a way launch tomcat via this extension that would mirror how tomcat would normally be launch, but I guess there are a bunch of extra bits in their startup process that would be a pain the mirror into your VM setup process.

**Comment by robstryker** [comment]
SO there's really only two things going on in the startup scripts. First, it needs to generate the command used to launch tomcat. The second, is it needs to pass an environment into the process. 

You can do both of these functions by editing the Server. To customize the launch string, you can modify the `args.override.boolean` property to true, the 'args.program.override.string' property if needbe (it shouldn't be needed), and the 'args.vm.override.string' property to customize the vm args that are sent. 

To customize the environment passed in, you would use the `mapProperty.launch.env` string. 

So I believe both of these can be accomplished with the existing tools available. 

Please feel free to close this issue if this is sufficient for you.

**Comment by imaperson** [comment]
I've written some tooling to help convert setenv.sh to a mapProperty.launch.env entry to try to make this process less tedious.  However, doing this manually is error prone.

When adding a tomcat server from an existing install on disk, would it be possible to default mapProperty.launch.env to the variable exports in setenv.sh?  I've started to peruse the code to see if I can make that modification myself.  Do you think such an effort would be worth adding, or should I not bother?

**Comment by robstryker** [comment]
Hrmm...  I think finding your way around the code might be challenging because it depends on the generic rsp framework which is up in the rsp-server repository. 

However, if you could make some standalone utility classes that could read setenv.sh and setenv.bat and create a map out of it, I could be tempted to make the changes required to allow the tomcat adapter to default to that map when the `mapProperty.launch.env` setting is not set for a given tomcat server. 

I think that'd be the most efficient use of your time because it wouldn't really require getting too familiar (or lost!) with the existing codebase, but still providing some great functionality that I could plug in and make use of!

What do you think??

**Comment by robstryker** [comment]
Closing this as there is a way to pass environment variables in and we will not use setenv.sh
