### ISSUE TITLE
Tomcat 9.0 server stop few minutes after start without any output (Clone)

### ISSUE THREAD

**Issue by Tenebrosful** [redhat-developer/rsp-server-community#206]
Pré-content: I already submit this issue at https://github.com/redhat-developer/vscode-rsp-ui/issues/282 but because i don't know which is the problem i add it here too

Hello,

I'm using the extension but there is a problem, the Tomcat server stop working after few minutes without any error or output logs.

I tested with CLI vanilla Tomcat or other extension like [Local Tomcat](https://github.com/snehaljha/local-tomcat) and everything looks fine.

`Windows 10 Pro 22H2`
`Tomcat 9.0`
`Runtime Server Protocol UI v0.24.7`

If i can share you any more details feel free to asking but like i said there is no output / logs (that i know) about this.

PS: It always display `Starting` even when startup finished and the server is available to use, maybe the RSP think the server didn't start and go timeout ? #138 

![image](https://github.com/redhat-developer/rsp-server-community/assets/48710891/bdd95b32-065b-47cc-94ab-0e79a817fd7d)
![image](https://github.com/redhat-developer/rsp-server-community/assets/48710891/0597c768-472f-4d37-9d5e-c2fa3f2b136e)

**Comment by robstryker** [comment]
Is your tomcat configured to run on port 8080 and host localhost? If not you'll need to edit your server adpater representation to tell it to try to connect on a different port.

Typically, when we start an app server, we wait for it to be started. If it never completes startup, we shut it down and cancel it. The way we know if it's completed is by checking it's host:port combo to see if its responsive.

If your tomcat is configured to run on port 8900 and we're busy checking 8080 to see if it's up, we obviously won't recognize the server is up and will think something is wrong.

**Comment by Tenebrosful** [comment]
Thanks, looks that was it, didn't know that my team binded it to an other port. Have a nice day !

**Comment by robstryker** [comment]
Just so you know, even if your team binds it to another port, you can configure the toolset to check that other port instead. 

You can right-click the server and select "Edit Server..." and add or change the "server.http.port" property to the value you desire.

**Comment by Tenebrosful** [comment]
Yeah that's what i did to don't change tomcat settings.

Things aside, is there a feature to made the server settings workspace ? Or each team member will have to edit it by them own ?

**Comment by robstryker** [comment]
Right now the server files are stored in a hard-coded path (mostly) in your home directory ~/.rsp/  with a bunch of stuff stored there, from actual RSP servers to the runtimes you download to the definitions of the settings for your local instance. 

One of the reasons (at this time) that storing the settings in a workplace is hard is because one of the primary fields in the server definition is the filesystem path of the installed tomcat or wildfly or whatever. And since these are typically downloaded either by the toolset itself (and thus stored in ~/.rsp) or by the user and placed somewhere in their home directory, sharing these files doesn't make a whole lot of sense. 

Every user would need to end up modifying the files anyway, because most home directories look like /home/jon or /home/rob. 

Because of all this, it's kinda hard to find a workflow that makes sharing these files reasonable or necessary, really.

**Comment by Tenebrosful** [comment]
hmmm, i see that, wasn't in my mind because at work everybody have the same path for everything so we could technically have a config in .vscode folder
