### ISSUE TITLE
Tomcat args.vm.override.string Not Working

### ISSUE THREAD

**Issue by BradyShober** [redhat-developer/rsp-server-community#58]
I am trying to specify a custom catalina.base argument in the args.vm.override.string field. Regardless of what arguments I enter here, only the defaults seem to be applied when running the server.

**Comment by robstryker** [comment]
Hi @BradyShober 
Are you making sure to set the  "args.override.boolean": "false",  to true instead of false? This lets the server know to use the overridden values instead.  

There is a bug with this, though, and I'm trying to release a fix ASAP, but see https://github.com/redhat-developer/rsp-server/pull/598   for details

**Comment by BradyShober** [comment]
@robstryker Ah okay, I set that to true and am seeing the new arguments are being used. I do believe I'm seeing that bug when trying to stop the server. Also, after setting a custom catalina.base, my WAR is not being deployed to the new location.

**Comment by robstryker** [comment]
Unfortunately right now the deployment folder is hard-coded in a json descriptor for the server type. I can try to update it so that it pulls from an override-able server field though.  

https://github.com/redhat-developer/rsp-server-community/pull/60

**Comment by robstryker** [comment]
Fixed it
